---
settings:
  name: Amazon FSx for NetApp ONTAP
  platform: cloud
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: ko-kr,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: NetApp ONTAP용 Amazon FSx 문서
    url: "/index.html"
  - title: 릴리스 정보
    url: "/whats-new.html"
  - title: 시작하십시오
    entries:
    - title: NetApp ONTAP용 Amazon FSx에 대해 알아보십시오
      url: "/start/concept-fsx-aws.html"
    - title: 빠른 시작
      url: "/start/task-getting-started-fsx.html"
    - title: 권한 설정
      url: "/requirements/task-setting-up-permissions-fsx.html"
    - title: 작업 환경을 만들거나 검색합니다
      url: "/use/task-creating-fsx-working-environment.html"
  - title: FSx for ONTAP 파일 시스템을 관리합니다
    url: "/use/task-manage-working-environment.html"
  - title: Tracker를 사용하여 작업을 모니터링합니다
    url: "/use/task-monitor-operations.html"
  - title: 작업 공간에서 파일 시스템을 제거합니다
    url: "/use/task-remove-filesystem.html"
  - title: 지식 및 지원
    entries:
    - title: 지원을 위해 등록하십시오
      url: "/support/task-support-registration.html"
    - title: 도움을 받으십시오
      url: "/support/task-get-help.html"
  - title: 법적 고지
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
