---
settings:
  name: Amazon FSx for NetApp ONTAP
  platform: cloud
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: ko-kr,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: NetApp ONTAP용 Amazon FSx 문서
    url: "/index.html"
  - title: 릴리스 정보
    url: "/whats-new.html"
  - title: 시작하십시오
    entries:
    - title: NetApp ONTAP용 Amazon FSx에 대해 알아보십시오
      url: "/start/concept-fsx-aws.html"
    - title: 빠른 시작
      url: "/start/task-getting-started-fsx.html"
  - title: 요구 사항
    entries:
    - title: 권한 설정
      url: "/requirements/task-setting-up-permissions-fsx.html"
    - title: 보안 그룹 규칙
      url: "/requirements/reference-security-groups-fsx.html"
  - title: NetApp ONTAP용 Amazon FSx를 사용합니다
    entries:
    - title: 작업 환경을 만들거나 검색합니다
      url: "/use/task-creating-fsx-working-environment.html"
    - title: 작업 환경 관리
      url: "/use/task-manage-working-environment.html"
    - title: 볼륨을 생성하고 마운트합니다
      url: "/use/task-add-fsx-volumes.html"
    - title: 볼륨 관리
      url: "/use/task-manage-fsx-volumes.html"
    - title: 스토리지 VM 추가 및 관리
      url: "/use/task-add-fsx-svm.html"
  - title: 지식 및 지원
    entries:
    - title: 지원을 위해 등록하십시오
      url: "/support/task-support-registration.html"
    - title: 도움을 받으십시오
      url: "/support/task-get-help.html"
  - title: 법적 고지
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
