= FSx for ONTAP 파일 시스템을 BlueXP 의 작업 공간과 연결합니다
:allow-uri-read: 




=== FSx for ONTAP 파일 시스템을 BlueXP 의 작업 공간과 연결합니다

2024년 11월 BlueXP  통합 이후 새로 생성된 FSx for ONTAP 파일 시스템이 BlueXP 의 한 작업 영역과 연결되지 않았습니다. 이제 FSx for ONTAP 파일 시스템을 생성하거나 검색할 때 BlueXP  계정 내의 한 작업 공간에 연결됩니다.

작업 영역과 연결되지 않은 기존 FSx for ONTAP 파일 시스템이 있는 경우 BlueXP 의 작업 영역과 연결할 수 있도록 도와 드리겠습니다. BlueXP  콘솔 내에서 수행할 수 link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-get-help.html#create-a-case-with-netapp-support["NetApp 지원에 케이스를 생성합니다"^]있습니다. Workload Factory * 를 서비스로 선택합니다.



=== BlueXP  캔버스에서 파일 시스템 제거

이제 BlueXP  캔버스의 작업 공간에서 FSx for ONTAP 파일 시스템을 제거할 수 있습니다. 이 작업을 수행하면 동일한 BlueXP  계정 내의 다른 작업 영역과 연결할 수 있도록 한 작업 영역에서 파일 시스템이 분리됩니다.

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-remove-filesystem.html["BlueXP 의 작업 공간에서 FSx for ONTAP 파일 시스템을 제거하는 방법에 대해 알아보십시오"^]



=== 추적기를 사용하여 작업을 모니터링하고 추적할 수 있습니다

새로운 모니터링 기능인 Tracker를 BlueXP  Amazon FSx for NetApp ONTAP에서 사용할 수 있습니다. Tracker를 사용하여 자격 증명, 저장소 및 링크 작업의 진행 상태 및 상태를 모니터링하고 추적하며, 작업 및 하위 작업에 대한 세부 정보를 검토하고, 문제 또는 장애를 진단하고, 실패한 작업에 대한 매개 변수를 편집하고, 실패한 작업을 재시도할 수 있습니다.

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-monitor-operations.html["BlueXP 에서 FSx for ONTAP 운영을 모니터링하고 추적하는 방법에 관해 알아보십시오"^]



=== BlueXP  워크로드에서 사용 가능한 CloudShell

CloudShell은 BlueXP  콘솔 내의 BlueXP  워크로드를 사용할 수 있습니다. CloudShell을 사용하면 BlueXP  계정에서 제공한 AWS 및 ONTAP 자격 증명을 사용하고 셸과 유사한 환경에서 AWS CLI 명령 또는 ONTAP CLI 명령을 실행할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html#before-you-begin["CloudShell을 사용합니다"^]
