---
sidebar: sidebar 
permalink: use/task-manage-fsx-volumes.html 
keywords: fsx for ontap, fsx, aws, delete volumes, delete nfs volumes, delete cifs volumes, tiering policy, mount path, get mount path, mount volume, delete volumes, snapshots, edit volume, clone volume, clone 
summary: 볼륨, 클론, 스냅샷을 관리하고 BlueXP를 사용하여 ONTAP용 FSx의 계층화 정책을 변경할 수 있습니다. 
---
= NetApp ONTAP용 Amazon FSx의 볼륨을 관리합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
볼륨, 클론, 스냅샷을 보고 관리할 수 있으며 BlueXP를 사용하여 ONTAP용 FSx의 계층화 정책을 변경할 수 있습니다.



== 볼륨 세부 정보를 봅니다

볼륨을 생성한 후 구성 세부 정보를 볼 수 있습니다.

. 작업 환경을 엽니다.
+

NOTE: 볼륨 이름 위로 마우스를 가져가면 볼륨 유형이 표시됩니다.

. 볼륨 탭을 열고 * 볼륨 관리 * 를 선택하여 * 볼륨 조치 * 메뉴를 엽니다.
. 볼륨 세부 정보 보기 * 를 선택합니다.




== 볼륨을 편집합니다

볼륨을 생성한 후에는 언제든지 수정할 수 있습니다.

.단계
. 작업 환경을 엽니다.
. 볼륨 탭을 열고 * 볼륨 관리 * 를 선택하여 * 볼륨 조치 * 메뉴를 엽니다.
. Edit volume settings * 를 선택합니다.
+
.. NFS의 경우 크기와 태그를 수정할 수 있습니다.
.. CIFS의 경우 필요에 따라 공유 이름, 사용자, 권한 및 스냅샷 정책을 수정할 수 있습니다.


. Apply * 를 선택합니다.




== 클론 볼륨

볼륨을 생성한 후 새 스냅샷으로부터 새 읽기-쓰기 볼륨을 생성할 수 있습니다.

.단계
. 작업 환경을 엽니다.
. 볼륨 탭을 열고 * 볼륨 관리 * 를 선택하여 * 볼륨 조치 * 메뉴를 엽니다.
. Clone the volume * 을 선택합니다.
. 복제된 볼륨의 이름을 입력합니다.
. 클론 * 을 선택합니다.




== 볼륨 태그 관리

볼륨 태그를 추가, 수정 또는 삭제할 수 있습니다. BlueXP에 추가된 태그는 AWS 콘솔에 반영됩니다. 태그를 AWS 콘솔과 동기화하는 데 최대 1시간이 걸릴 수 있습니다.

.단계
. 작업 환경을 엽니다.
. 볼륨 탭을 열고 * 볼륨 관리 * 를 선택하여 * 볼륨 조치 * 메뉴를 엽니다.
. 볼륨 태그 관리 * 를 선택합니다.
. 변경 사항을 적용하려면 * 저장 * 을 선택합니다.




== 스냅샷 복사본을 관리합니다

Snapshot 복사본은 볼륨의 시점 복사본을 제공합니다. 스냅샷 복사본을 생성하고 데이터를 새 볼륨으로 복원합니다.

.단계
. 작업 환경을 엽니다.
. 볼륨 탭을 열고 * 볼륨 관리 * 를 선택하여 * 보호 조치 * 메뉴를 엽니다.
. 사용 가능한 옵션 중 하나를 선택하여 스냅샷 복사본을 관리합니다.
+
** * 스냅샷 복사본 생성 *
** * 스냅샷 복사본에서 복원 *


. 프롬프트에 따라 선택한 작업을 완료합니다.




== 계층화 정책을 변경합니다

볼륨에 대한 계층화 정책을 변경합니다.

.단계
. 작업 환경을 엽니다.
. 볼륨 탭을 열고 * 볼륨 관리 * 를 선택하여 * 고급 작업 * 메뉴를 엽니다.
. 계층화 정책 변경 * 을 선택합니다.
. 새 볼륨 계층화 정책을 선택하고 * Change * 를 클릭합니다.




== 데이터 복제 및 동기화

BlueXP를 사용하여 스토리지 환경 간에 데이터를 복제할 수 있습니다. ONTAP 복제에 대해 FSx를 구성하려면 를 참조하십시오 https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["시스템 간 데이터 복제"^].

BlueXP 복사 및 동기화를 사용하여 동기화 관계를 생성할 수 있습니다. 동기화 관계를 구성하려면 를 참조하십시오 https://docs.netapp.com/us-en/bluexp-copy-sync/task-creating-relationships.html["동기화 관계를 생성합니다"^].



== 볼륨을 삭제합니다

더 이상 필요하지 않은 볼륨을 삭제합니다.

.시작하기 전에
BlueXP를 사용하여 이전에 SnapMirror 관계의 일부였던 볼륨을 삭제할 수 없습니다. SnapMirror 볼륨은 AWS 관리 콘솔 또는 CLI를 사용하여 삭제해야 합니다.

.단계
. 작업 환경을 엽니다.
. 볼륨 탭을 열고 * 볼륨 관리 * 를 선택하여 * 볼륨 조치 * 메뉴를 엽니다.
. 볼륨 삭제 * 를 선택합니다.
. 작업 환경 이름을 입력하고 볼륨 삭제를 확인합니다. BlueXP에서 볼륨을 완전히 제거하는 데 최대 1시간이 걸릴 수 있습니다.



NOTE: 복제된 볼륨을 삭제하려고 하면 오류가 발생합니다.
