---
sidebar: sidebar 
permalink: start/concept-fsx-aws.html 
keywords: Amazon FSx for NetApp ONTAP, volumes, aws, access key, secret key, cloud manager 
summary: NetApp ONTAP용 Amazon FSx는 고객이 NetApp의 ONTAP 스토리지 운영 체제가 제공하는 파일 시스템을 시작하고 실행할 수 있도록 하는 완전 관리형 서비스입니다. ONTAP용 FSX는 NetApp 고객이 현재 사내에서 사용하는 것과 동일한 기능, 성능 및 관리 기능을 기본 AWS 서비스의 단순성, 민첩성, 보안 및 확장성으로 제공합니다. 
---
= NetApp ONTAP용 Amazon FSx에 대해 알아보십시오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["NetApp ONTAP용 Amazon FSx"^] 는 고객이 NetApp의 ONTAP 스토리지 운영 체제가 제공하는 파일 시스템을 실행하고 실행할 수 있도록 하는 완전 관리형 서비스입니다. ONTAP용 FSX는 NetApp 고객이 사내에서 사용하는 것과 동일한 기능, 성능 및 관리 기능을 기본 AWS 서비스의 단순성, 민첩성, 보안 및 확장성으로 제공합니다.



== 피처

* 스토리지 디바이스, 소프트웨어 또는 백업을 구성하거나 관리할 필요가 없습니다.
* CIFS, NFSv3, NFSv4.x 및 SMB v2.0-v3.1.1 프로토콜 지원
* 자주 액세스하지 않는(IA) 스토리지 계층을 사용하여 저렴한 비용으로 사실상 제한 없는 데이터 스토리지 용량을 확보할 수 있습니다.
* Oracle RAC를 포함하여 지연 시간에 민감한 애플리케이션에서 실행되도록 인증받았습니다.
* 번들 및 용량제 가격 선택 가능




== BlueXP의 추가 기능

* 사용 link:https://docs.netapp.com/us-en/cloud-manager-family/["BlueXP"^] (클라우드 관리자) 및 AWS의 Connector를 사용하면 볼륨을 생성 및 관리하고, 데이터를 복제하고, ONTAP용 FSx를 BlueXP 분류, BlueXP 복사 및 동기화(Cloud Sync)와 같은 NetApp 클라우드 서비스와 통합할 수 있습니다.
* AI(인공 지능) 기반 기술을 사용하는 BlueXP 분류(클라우드 데이터 감지)는 데이터 컨텍스트를 이해하고 FSx for ONTAP 계정에 있는 중요한 데이터를 식별하는 데 도움이 됩니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/concept-cloud-compliance.html["자세한 정보"^].
* BlueXP 복사 및 동기화를 사용하여 클라우드 또는 온프레미스 모든 대상으로 데이터 마이그레이션을 자동화할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-sync/concept-cloud-sync.html["자세한 정보"^]




== 비용

ONTAP용 FSx 계정은 BlueXP가 아니라 AWS에서 관리합니다. 을 참조하십시오 https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["NetApp ONTAP용 Amazon FSx 시작 가이드"^].

AWS에서 Connector를 사용하는 것과 BlueXP 복사 및 동기화, BlueXP 분류와 같은 옵션 데이터 서비스를 사용하는 경우 추가 비용이 발생합니다.



== 지원 지역

https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["지원되는 아마존 지역을 봅니다."^]



== 도움말 보기

NetApp ONTAP용 Amazon FSx는 AWS 퍼스트 파티 솔루션입니다. Amazon FSx for NetApp ONTAP 파일 시스템, 인프라 또는 이 서비스를 사용하는 솔루션과 관련된 질문 또는 기술 지원 문제가 있는 경우 AWS 콘솔의 지원 센터를 사용하여 AWS에 지원 케이스를 여십시오. “FSx for ONTAP” 서비스와 적절한 범주를 선택합니다. AWS 지원 케이스를 생성하는 데 필요한 나머지 정보를 제공합니다.

BlueXP 또는 BlueXP 스토리지 솔루션 및 서비스에 대한 일반적인 질문은 인라인 BlueXP 채팅으로 시작할 수 있습니다.

BlueXP 또는 BlueXP 스토리지 솔루션 및 서비스와 관련된 기술 지원 문제의 경우 BlueXP 계정 수준의 일련 번호를 사용하여 NetApp 지원 티켓을 열 수 있습니다. 이 작업을 수행해야 합니다 link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/support/task-support-registration.html["BlueXP 계정을 등록합니다"^] 지원을 활성화합니다.
