---
sidebar: sidebar 
permalink: start/concept-fsx-aws.html 
keywords: Amazon FSx for NetApp ONTAP, volumes, aws, access key, secret key, cloud manager 
summary: Amazon FSx for NetApp ONTAP은 고객이 NetApp의 ONTAP 스토리지 운영 체제에 기반한 파일 시스템을 시작하고 실행할 수 있도록 지원하는 완전 관리형 서비스입니다. 
---
= NetApp ONTAP용 Amazon FSx에 대해 알아보십시오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["NetApp ONTAP용 Amazon FSx"^] 는 고객이 NetApp ONTAP 스토리지 운영 체제에 기반한 파일 시스템을 시작하고 실행할 수 있도록 지원하는 완전 관리형 서비스입니다. ONTAP용 FSX는 NetApp 고객이 사내에서 사용하는 것과 동일한 기능, 성능 및 관리 기능을 기본 AWS 서비스의 단순성, 민첩성, 보안 및 확장성으로 제공합니다.



== BlueXP 에서 FSx for ONTAP 사용

BlueXP  캔버스에서 FSx for ONTAP 작업 환경을 만들고 검색하고 System Manager 및 기타 BlueXP  서비스를 사용할 수 있습니다. Amazon FSx for NetApp ONTAP에서 실행되는 ONTAP 작업 환경과 워크로드를 관리하려면 를 사용합니다. https://docs.netapp.com/us-en/workload-fsx-ontap/index.html["BlueXP  워크로드 공장"^]

link:../use/task-creating-fsx-working-environment.html["BlueXP 에서 FSx for ONTAP 작업 환경을 생성하고 이 환경을 파악하는 방법에 대해 알아보십시오"^]..



== 피처

* 스토리지 디바이스, 소프트웨어 또는 백업을 구성하거나 관리할 필요가 없습니다.
* CIFS, iSCSI, NFSv3, NFSv4.x 및 https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html["S3를 참조하십시오"^] SMB v2.0-v3.1.1 프로토콜 지원
* 자주 액세스하지 않는(IA) 스토리지 계층을 사용하여 저렴한 비용으로 사실상 제한 없는 데이터 스토리지 용량을 확보할 수 있습니다.
* Oracle RAC를 포함하여 지연 시간에 민감한 애플리케이션에서 실행되도록 인증받았습니다.
* 번들 및 용량제 가격 선택 가능




== BlueXP의 추가 기능

* FSx for ONTAP은 BlueXP  SaaS 계층을 활용하여 전체 기능을 제공하는 in_standard_mode에서 BlueXP 을 사용할 때 지원됩니다. _Restricted_mode 및 _private_mode는 지원되지 않습니다.
+
을 참조하십시오 link:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["BlueXP 배포 모드"^] 를 참조하십시오.

* 사용 link:https://docs.netapp.com/us-en/bluexp-family/["BlueXP"^] AWS의 Connector를 사용하면 볼륨을 생성 및 관리하고, 데이터를 복제하고, ONTAP용 FSx를 BlueXP 분류, BlueXP 복사 및 동기화 등의 NetApp 클라우드 서비스와 통합할 수 있습니다.
* AI(인공 지능) 기반 기술을 사용하는 BlueXP 분류는 데이터 컨텍스트를 이해하고 FSx for ONTAP 계정에 있는 중요한 데이터를 식별하는 데 도움이 됩니다. https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["자세한 정보"^].
* BlueXP 복사 및 동기화를 사용하여 클라우드 또는 온프레미스 모든 대상으로 데이터 마이그레이션을 자동화할 수 있습니다. https://docs.netapp.com/us-en/bluexp-copy-sync/concept-cloud-sync.html["자세한 정보"^]




== 커넥터와 링크는 모든 FSx for ONTAP 기능의 잠금을 해제합니다

커넥터와 링크를 통해 BlueXP 와 Amazon FSx for NetApp ONTAP 작업 환경 간의 연결 및 신뢰 관계를 구축할 수 있습니다. BlueXP  Connector는 클라우드 또는 온프레미스 네트워크에서 실행되는 NetApp 소프트웨어이며 AWS Lambda를 사용하여 NetApp 코드를 실행합니다. BlueXP 에서 시작하거나 FSx for ONTAP 작업 환경을 생성하기 위한 커넥터 또는 링크가 필요하지 않지만, FSx for ONTAP 기능을 최대한 활용하려면 커넥터 또는 링크를 사용해야 합니다.

다음 기능을 사용하려면 커넥터 또는 링크가 필요합니다.

* FSx for ONTAP 파일 시스템에 설치된 ONTAP 버전을 표시합니다
* 시스템에서 iSCSI 볼륨을 관리합니다
* 볼륨에 대한 자동 확장 기능을 설정 및 해제합니다
* 스냅샷 정책을 생성하고 관리합니다
* 파일 시스템 간 복제 관계 구성 및 볼륨 복제
* 백업 관계를 구성하고 볼륨 데이터를 클라우드 스토리지에 백업합니다
* 파일 시스템 내의 볼륨 클론 생성
* ONTAP에서 직접 추가 메트릭 표시(기본 메트릭은 Amazon CloudWatch에서 수집)
* NFS 엑스포트 정책 관리


커넥터 및 링크 및 사용 시기에 대해 자세히 알아보십시오.

* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html["커넥터에 대해 자세히 알아보십시오"^]..
* https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["링크에 대해 자세히 알아보세요"^]..




== 비용

ONTAP용 FSx 계정은 BlueXP가 아니라 AWS에서 관리합니다. 을 참조하십시오 https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["NetApp ONTAP용 Amazon FSx 시작 가이드"^].

AWS에서 Connector를 사용하는 것과 BlueXP 복사 및 동기화, BlueXP 분류와 같은 옵션 데이터 서비스를 사용하는 경우 추가 비용이 발생합니다.



== 지원 지역

https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["지원되는 아마존 지역을 봅니다."^]



== 도움말 보기

NetApp ONTAP용 Amazon FSx는 AWS 퍼스트 파티 솔루션입니다. 이 서비스를 사용하는 FSx for ONTAP 파일 시스템, 인프라 또는 솔루션과 관련하여 궁금한 사항이나 기술 지원 문제가 있는 경우 AWS 관리 콘솔의 지원 센터를 사용하여 AWS에 지원 케이스를 여십시오. "FSx for ONTAP" 서비스 및 적절한 범주를 선택합니다. AWS 지원 케이스를 생성하는 데 필요한 나머지 정보를 제공합니다.

BlueXP 또는 BlueXP 스토리지 솔루션 및 서비스에 대한 일반적인 질문은 인라인 BlueXP 채팅으로 시작할 수 있습니다.

BlueXP  또는 BlueXP  스토리지 솔루션 및 서비스와 관련된 기술 지원 문제는 BlueXP  조직별 일련 번호를 사용하여 NetApp 지원 티켓을 개설할 수 있습니다. 지원을 활성화해야 link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/support/task-support-registration.html["BlueXP  조직을 등록합니다"^]합니다.
